config/routes.rb
Rails.application.routes.draw do
  get 'paginas_estaticas/inicio'

  get 'paginas_estaticas/ayuda'

  resources :chuits

  resources :usuarios

  get '/nuevo_chuit' => 'chuits#new'
  
  get 'listaUsuarios' => 'usuarios#index'
  
  get '/loosers'  => redirect('/usuarios')
  
  root 'paginas_estaticas#inicio'
  
  get 'usuarios/:nombre' => 'usuarios#index', as:'lista'
  
  get 'inicio' => 'paginas_estaticas#inicio'
  
  get 'ayuda' => 'paginas_estaticas#ayuda'
  

end

app/models/chuit.rb
class Chuit < ActiveRecord::Base
  belongs_to :usuario
  validates :text, :length =>{:maximum =>140}
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_many :chuits
  validates :nombre, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chuits_controller.rb
class ChuitsController < ApplicationController
  before_action :set_chuit, only: [:show, :edit, :update, :destroy]

  # GET /chuits
  # GET /chuits.json
  def index
    @chuits = Chuit.all
  end

  # GET /chuits/1
  # GET /chuits/1.json
  def show
  end

  # GET /chuits/new
  def new
    @chuit = Chuit.new
  end

  # GET /chuits/1/edit
  def edit
    if @chuit.usuario_id != session[:usuario_id]
      flash[:notice] = "No puedes editar este Chuit"
      redirect_to(chuits_path)
    end
  end

  # POST /chuits
  # POST /chuits.json
  def create
    @chuit = Chuit.new(chuit_params)

    respond_to do |format|
      if @chuit.save
        format.html { redirect_to @chuit, notice: 'Chuit was successfully created.' }
        format.json { render :show, status: :created, location: @chuit }
      else
        format.html { render :new }
        format.json { render json: @chuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chuits/1
  # PATCH/PUT /chuits/1.json
  def update
    respond_to do |format|
      if @chuit.update(chuit_params)
        format.html { redirect_to @chuit, notice: 'Chuit was successfully updated.' }
        format.json { render :show, status: :ok, location: @chuit }
      else
        format.html { render :edit }
        format.json { render json: @chuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chuits/1
  # DELETE /chuits/1.json
  def destroy
    @chuit.destroy
    respond_to do |format|
      format.html { redirect_to chuits_url, notice: 'Chuit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chuit
      @chuit = Chuit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chuit_params
      params.require(:chuit).permit(:text, :usuario_id)
    end
end

app/controllers/paginas_estaticas_controller.rb
class PaginasEstaticasController < ApplicationController
  def inicio
  end

  def ayuda
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    if @usuario.chuits.empty?
      redirect_to (usuarios_path)
    else
      render action: :show
    end
    #debugger
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chuits_helper.rb
module ChuitsHelper
end

app/helpers/paginas_estaticas_helper.rb
module PaginasEstaticasHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
  
  def gravatar_for(usuario)
    gravatar_id = Digest::MD5::hexdigest(usuario.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: usuario.nombre, class:"gravatar")
  end
end

app/views/chuits/_form.html.erb
<%= form_for(@chuit) do |f| %>
  <% if @chuit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chuit.errors.count, "error") %> prohibited this chuit from being saved:</h2>

      <ul>
      <% @chuit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= f.number_field :usuario_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chuits/edit.html.erb
<h1>Editing Chuit</h1>

<%= render 'form' %>

<%= link_to 'Show', @chuit %> |
<%= link_to 'Back', chuits_path %>

app/views/chuits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chuits</h1>
<% if @chuits.count > 0  %>
<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chuits.each do |chuit| %>
      <tr>
        <td><%= chuit.usuario.nombre %></td> 
        <td><%= chuit.text %></td>
        <td><%= chuit.usuario_id %></td>
        <td><%= link_to 'Show', chuit %></td>
        <td><%= link_to 'Edit', edit_chuit_path(chuit) %></td>
        <td><%= link_to 'Destroy', chuit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <em>NO HAY CHUITS </em>
<%  end %>
<br>

<%= link_to 'New Chuit', new_chuit_path %>

app/views/chuits/new.html.erb
<h1>New Chuit</h1>

<%= render 'form' %>

<%= link_to 'Back', chuits_path %>

app/views/chuits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @chuit.text %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @chuit.usuario_id %>
</p>

<%= link_to 'Edit', edit_chuit_path(@chuit) %> |
<%= link_to 'Back', chuits_path %>

app/views/layouts/_cabecera.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "Inicio", inicio_path, id:"logo" %>
        <ul class="nav navbar-nav navbar-right">
            <li> <%= link_to "Iniciar Sesión", ayuda_path %></li>
        </ul>
    </div> 
</header>

app/views/layouts/_pie.html.erb
<footer class="footer">
    <small>
        Mejor que <a href="http://www.twitter.com/"> Twitter</a> en muchos aspectos
        by Jorge Cisneros
    </small>
      <nav>
          <ul>
              <li> <%= link_to "Acerca de", '#' %></li>
              <li> <%= link_to "Inicio", '#' %></li>
              <li> Hazte Chollower</li>
          </ul>
      </nav>    
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chuitter: la red social de no moda</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/cabecera' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/pie' %>
    <%= debug(params) if Rails.env.development?  %>
</body>
</html>

app/views/paginas_estaticas/ayuda.html.erb
<h1>PaginasEstaticas#ayuda</h1>
<p>Find me in app/views/paginas_estaticas/ayuda.html.erb</p>

app/views/paginas_estaticas/inicio.html.erb
<div class="center jumbotron">
    <h1>
      Bienvenido a Chuitter!!
    </h1>
    
    <h2>
        Esto es el inicio de una gran amistad
            
    </h2>
</div>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Usuarios</h1>

<table bgcolor="#ccc" border="1">
    <thead>
        <tr>
            <th>Cuenta de chuits</th>
            <th>¿Tiene más de un chuit?</th>
            <th>ID</th>
            <th>Nombre</th>
            <th>Email</th>
            <th colspan="3">Acciones </th>
        </tr>
    </thead>

    <tbody>
        <% @usuarios.each do |usuario| %>
          <tr>
              <td><%= usuario.chuits.count %></td>
              <td><%= 
                  if usuario.chuits.count > 1
                    "!Eres guay!"
                    else
                    "!Perdedor!"
                    end
                %></td>
              <td><%= usuario.id %></td>
              <td><%= usuario.nombre %></td>
              <td><%= usuario.email %></td>
              <td><%= link_to 'Mostrar', usuario %></td>
              <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
              <td><%= link_to 'Borrar', usuario, method: :delete, data: { confirm: 'ESTAS SEGURO??' } %></td>
          </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<div>
    
<% provide(:title, @usuario.nombre) %>

    <h1>
        <%= gravatar_for @usuario %>
        <%= @usuario.nombre %>
    </h1>
</div>